_format_version: "3.0"
_transform: true

services:
  - name: auth-service
    url: http://ms1-auth:8001
    routes:
      - name: auth-route
        paths:
          - /auth-service
        strip_path: true
    plugins:
      - name: rate-limiting
        config:
          minute: 60
          policy: local

  - name: ingestor-service
    url: http://ms2-ingestor:8002
    routes:
      - name: ingestor-route
        paths:
          - /ingestor-service
        strip_path: true

  - name: ai-service
    url: http://ms3-ai-engine:8003
    routes:
      - name: ai-route
        paths:
          - /ai-service
        strip_path: true

  - name: alert-service
    url: http://ms4-alert:8004
    routes:
      - name: alert-route
        paths:
          - /alert-service
        strip_path: true

  - name: maintenance-service
    url: http://ms5-maintenance:8005
    routes:
      - name: maintenance-route
        paths:
          - /maintenance-service
        strip_path: true

  - name: machine-service
    url: http://ms6-machine:8006
    routes:
      - name: machine-route
        paths:
          - /machine-service
        strip_path: true

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
      exposed_headers:
        - Authorization
      credentials: true
      max_age: 3600

  - name: prometheus
